apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: abimasantos/api-produto
          ports:
          - containerPort: 80
            name: http
          imagePullPolicy: Always 
          env:
          - name: Mongo__Host
            value: "mongo-service"
          - name: mongo__User
            value: "mongouser"
          - name: Mongo__Password
            value: "mongopwd"
          - name: Mongo__Port
            value: "27017"
          - name: Mongo__DataBase
            value: "admin"